### PR TITLE
Add IPv6 support for TCPPacket

### PR DESCRIPTION
**Pull request by sdaubert**
Add support for TCPPacket over IPv6 as this was done for UDPPacket.
Factorize some code common to UDPPacket, TCPPacket, ICMPPacket and ICMPv6Packet (checksum computation).
Replace #143.

### CODE REVIEW

**Comment by dimriou** [comment]
Hi there,
I wanted to use PacketFu with IPv6 support for TCP Packets and I was wondering when this PR is gonna get merged with the master branch?
Thanks!

**Comment by dionyziz** [comment]
Hi guys – do we have any news with this? Is there any concern with the code causing this not to get merged? If there's any issue with this code, we'll be happy to reiterate on it and improve it so that it gets merged upstream. We need to use packetfu's IPv6 capabilities in bettercap, so this patch is critical for our work. Thanks!

**Comment by claudijd** [comment]
@dionyziz no news yet, I've been swamped with other non-packetfu related things and I haven't been able to make time to look at this.  I'm hoping to get back to it over the winter months, but I realize that's not very helpful to you.

**Comment by dionyziz** [comment]
@claudijd Thanks for getting back to us. We're eagerly waiting for your code review. In the meantime, @dimriou will start working on an ICMP6 patch for packetfu, so that you can review both of these together when you get the time ;)

**Comment by claudijd** [comment]
Hey guys, basically I'm a terrible person and let this sit way too long.  Landed!

**Comment by picatz** [comment]
@claudijd I ❤️  you.

**Pull request merged**
