### PR TITLE
Ruby 2.4 updates + more tests, less whitespace

### PR DESCRIPTION
**Pull request by busterb**
Thanks to the big MRI change in Ruby 2.4, Bignum is out, Integer is in. There was very little actual code that needed updating in packetfu, but I did expand Travis out to test more Ruby versions anyway.

### CODE REVIEW

**Comment by todb-r7** [comment]
Here's the reference:

https://bugs.ruby-lang.org/issues/12739

I just eyeball reviewed @busterb's changes, looks like he caught all the comparisons so now anything like `foo == Fixnum` is `foo.kind_of? Integer`, as well as all the class declarations using `Fixnum`.

**Comment by todb-r7** [comment]
So, when merging, I do end up with:

```
/home/todb/.rvm/gems/ruby-2.4.0/gems/simplecov-0.12.0/lib/simplecov/configuration.rb:207: warning: constant ::Fixnum is deprecated
[Coveralls] Outside the CI environment, not sending data.
/home/todb/.rvm/gems/ruby-2.4.0/gems/simplecov-0.12.0/lib/simplecov/configuration.rb:207: warning: constant ::Fixnum is deprecated
/home/todb/.rvm/gems/ruby-2.4.0/gems/simplecov-0.12.0/lib/simplecov/source_file.rb:29: warning: constant ::Fixnum is deprecated
/home/todb/.rvm/gems/ruby-2.4.0/gems/simplecov-0.12.0/lib/simplecov/source_file.rb:30: warning: constant ::Fixnum is deprecated
```

This doesn't seem to be a huge deal, and ought to be fixed upstream.

**Comment by busterb** [comment]
Thanks. Yes, simplecov is already fixed in 0.13.0. It's not immediately clear to me why it's not being pulled in yet, since I don't see any fixed versions in packetfu's gemspec.

**Comment by todb-r7** [comment]
I don't see any reason not to publish a new gem, PacketFu 1.12 (updating from 1.12-pre). @busterb can you eyeball #162 ?

**Pull request merged**
