### PR TITLE
Add arp cache in PacketFu::Utils

### LINKED ISSUE #14: Need a cross-platform way to get at the ARP table
It wouldn't be native Ruby, but it would be nice to get at the local ARP table. Why re-arp things when the OS already knows about it? For example:

````ruby
1.9.3p125 :002 > arp_table = `arp -na`
 => "? (173.255.206.1) at 00:00:0c:9f:f0:01 [ether] on eth0\n" 
1.9.3p125 :007 > arp_table.split(/\n/).map {|x| tbl = x.split; [tbl[1],tbl[3]]}
 => [["(173.255.206.1)", "00:00:0c:9f:f0:01"]] 
1.9.3p125 :008 > exit
todb@presto:~$ 

````

You'd certainly want this returned as a hash, since IP addresses only get the one MAC address.

Suggested via e-mail by Charles Sullivan.

### PR DESCRIPTION
**Pull request by sdaubert**
Add a new method PacketFu::Utils.arp_cache which get ARP cache from OS.

Modify PacketFu::Utils.arp to use Utils.arp_cache by default to avoid sending ARP packet on wire if IP address is in ARP cache.

Resolve #14

### CODE REVIEW

**Comment by claudijd** [comment]
@sdaubert thanks for the contribution, could you please provide specs for your changes here? It will ensure that we don't break it down the line in future versions.  Thanks!

**Comment by sdaubert** [comment]
I am trying to write some specs, but I have a problem with PacketFu::Capture which seems to not capture outgoing ARP packets (spec: check that when cache is activated and MAC is in local cache,  no ARP request should be sent).

**Comment by sdaubert** [comment]
Finally, i write specs using tcpdump, as i have not succeed to use PacketFu::Capture.

**Comment by sdaubert** [comment]
The Travis CI build failed as it is not run as root. But this is necessary to capture packets...

**Comment by claudijd** [comment]
@sdaubert I think your best bet here is to provide an abstraction layer so you can spec what we expect to see from arp -a from the system in response.  Since we are likely to have multiple examples of this per OS, having this layer helps with specing out the various scenarios we support.  We have a similar strategy for this with "ifconfig" parsing in utils.rb that could take and we now have specs that demonstrate how to go about that.  We could also attack this from a mock perspective, but I haven't gotten around to that yet.

**Comment by sdaubert** [comment]
@claudijd Write new specs inspired from ifconfig ones. But now, i cannot test case where address is not in ARP cache.

**Comment by claudijd** [comment]
@sdaubert great job on the updated specs for the ARP logic, that is exactly what I was looking for.   We can pass on the specs for the active on-the-wire stuff, it's something we don't do a good job yet in most of PacketFu that I hope to improve over time.  I'll land this shortly, thanks again!

**Pull request merged**
