### PR TITLE
Add support for OpenBSD

### PR DESCRIPTION
**Pull request by angelosk**
Support for OpenBSD --- pretty similar to FreeBSD, except for the ethernet address line.

### CODE REVIEW

**Comment by claudijd** [comment]
@angelosk thanks for the submission and sorry for the delay.  I just recently put a patch on master to fix the CI-builds that were failing in 1.9.3.  Also, would you mind adding an example case for OpenBSD in ./spec/utils_spec.rb? just to show that your new logic works as expected?

If not, could you just send me a copy of the ifconfig data from a OpenBSD system so I can add it and make sure it passes before this is merged?

**Comment by angelosk** [comment]
Hi, I can't get to this right now, but here's an ifconfig from OpenBSD in case you can do it:

em0: flags=8b43<UP,BROADCAST,RUNNING,PROMISC,ALLMULTI,SIMPLEX,MULTICAST> mtu 1500
        lladdr 00:01:02:03:04:05
        priority: 0
        groups: egress
        media: Ethernet autoselect (1000baseT full-duplex,rxpause,txpause)
        status: active
        inet 10.0.0.1 netmask 0xffffff00 broadcast 10.0.0.255

**Comment by angelosk** [comment]
Hmm, the sanitizer ate my homework (or the previous message). Here's the ifconfig line again:

em0: flags=8b43\<UP,BROADCAST,RUNNING,PROMISC,ALLMULTI,SIMPLEX,MULTICAST\> mtu 1500
        lladdr 00:01:02:03:04:05
        priority: 0
        groups: egress
        media: Ethernet autoselect (1000baseT full-duplex,rxpause,txpause)
        status: active
        inet 10.0.0.1 netmask 0xffffff00 broadcast 10.0.0.255

**Comment by claudijd** [comment]
@angelosk just landed, used your OpenBSD output to add unit-tests to make sure it works as expected (https://github.com/packetfu/packetfu/commit/1d9931e792eabcae6533e55f12ae8af190c19dfa)

Thanks again for the contribution!

**Pull request merged**
